# Generated by Django 6.0.4 on 2026-04-29 09:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('travel_type', models.CharField(choices=[('Safari', 'Safari'), ('MICE', 'MICE')], default='Safari', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('travel_type', models.CharField(choices=[('Safari', 'Safari'), ('MICE', 'MICE')], max_length=10)),
                ('style', models.CharField(choices=[('Budget-friendly', 'Budget-friendly'), ('Standard', 'Standard'), ('Luxury', 'Luxury')], default='Standard', max_length=20)),
                ('interest', models.CharField(max_length=50)),
                ('time_slot', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Full-day', 'Full-day'), ('Flexible', 'Flexible')], default='Flexible', max_length=20)),
                ('day_suitability', models.CharField(choices=[('Arrival', 'Arrival'), ('Mid-trip', 'Mid-trip'), ('Departure', 'Departure'), ('Any', 'Any')], default='Any', max_length=20)),
                ('intensity', models.CharField(choices=[('Light', 'Light'), ('Moderate', 'Moderate'), ('Heavy', 'Heavy')], default='Moderate', max_length=20)),
                ('base_score', models.IntegerField(default=1)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,25}$', 'Invalid phone format')])),
                ('travel_type', models.CharField(choices=[('Safari', 'Safari'), ('MICE', 'MICE')], max_length=10)),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('travel_style', models.CharField(choices=[('Budget-friendly', 'Budget-friendly'), ('Standard', 'Standard'), ('Luxury', 'Luxury')], max_length=20)),
                ('group_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('interests', models.JSONField(default=list)),
                ('status', models.CharField(default='Draft Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='core.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('time_slot', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposal_notes', models.TextField(blank=True)),
                ('finalized', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_response', to='core.inquiry')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
