# Generated by Django 5.2.15 on 2026-06-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="inquiry",
            options={"verbose_name_plural": "Inquiries"},
        ),
        migrations.AlterModelOptions(
            name="itinerary",
            options={"verbose_name_plural": "Itineraries"},
        ),
        migrations.AddField(
            model_name="inquiry",
            name="additional_interests",
            field=models.TextField(blank=True),
        ),
    ]
