# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_activity_options_alter_inquiry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="activities_per_day",
            field=models.PositiveSmallIntegerField(choices=[(1, "1 activity per day"), (2, "2 activities per day"), (3, "3 activities per day")], default=3),
        ),
    ]
